version: "3.7"

services:
  web:
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000